version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v10-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v10-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v10-dependencies-{{ checksum "package.json" }}
      # run tests!
      # - run:
      #     name: v10 tests
      #     command: |
      #         mkdir -p ~/repo/certs/b
      #         mkdir -p ~/repo/certs/c
      #         echo "$LND_MACAROON_B_BASE64" | base64 --decode > $LND_MACAROON_B
      #         echo "$LND_TLSCERT_B_BASE64" | base64 --decode > $LND_TLSCERT_B
      #         echo "$LND_MACAROON_C_BASE64" | base64 --decode > $LND_MACAROON_C
      #         echo "$LND_TLSCERT_C_BASE64" | base64 --decode > $LND_TLSCERT_C
      #         npm test
      # test
      - run: npm t
      # lint
      - run: npm run lint
      # build
      - run: npm run build
      # upload coverage to codecov.io
      - run: npx codecov
      - persist_to_workspace:
          root: ~/repo
          paths: .

  # Make sure the tests work on Node v8 as well
  build_node_v8:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo_v8
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v8-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v8-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v8-dependencies-{{ checksum "package.json" }}
      # # run tests!
      # - run:
      #     name: v8 tests
      #     command: |
      #       mkdir -p ~/repo/certs/b
      #       mkdir -p ~/repo/certs/c
      #       echo "$LND_MACAROON_B_BASE64" | base64 --decode > $LND_MACAROON_B
      #       echo "$LND_TLSCERT_B_BASE64" | base64 --decode > $LND_TLSCERT_B
      #       echo "$LND_MACAROON_C_BASE64" | base64 --decode > $LND_MACAROON_C
      #       echo "$LND_TLSCERT_C_BASE64" | base64 --decode > $LND_TLSCERT_C
      #       npm test
      # test
      - run: npm t
      # lint
      - run: npm run lint

  publish:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - build_node_v8:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build_node_v8
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
